<% # Make sure the local copy of the driver is loaded %>
<% lib = File.expand_path('../lib', __FILE__) %>
<% $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib) %>
---
driver:
  name: docker
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash

transport:
  name: docker

provisioner:
  name: dummy

platforms:
- name: amazonlinux-2
- name: ubuntu-18.04
- name: ubuntu-20.04
- name: fedora-latest
  driver:
    provision_command:
    - yum install libxcrypt-compat -y
    - curl -L https://www.chef.io/chef/install.sh | bash
    - yum install ruby-coveralls 
- name: centos-8
- name: oraclelinux-7
- name: rockylinux-8
- name: debian-10

suites:
- name: default
  excludes: [arch]
- name: context
  excludes: [arch]
  driver:
    build_context: false
- name: capabilities
  includes: [debian-10,ubuntu-20.04]
  driver:
    provision_command:
    - curl -L https://www.chef.io/chef/install.sh | bash
    - apt-get install -y net-tools
    - apt-get install ruby-coveralls
    - coveralls open
    cap_drop:
    - NET_ADMIN
- name: arm64
  excludes: [debian-9]
  driver:
    docker_platform: linux/arm64
- name: amd64
  driver:
    docker_platform: linux/amd64
- name: inspec
  driver:
    provision_command: true
  verifier:
    name: inspec
