---
- os: linux
dist: xenial
        jdk: openjdk11
        env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
matrix:
  include:
    - os: linux
      rvm: 2.4.9
      dist: xenial
      env: COVERALLS_TOKEN="coveralls:report"
      language: ruby
      cache: bundler
      before_install:
        - gem update --system
        - gem install bundler
        - gem install coveralls -v 0.8.15
      script:
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec kitchen list
services:
  - docker
after_success:
  - coveralls report
